### ISSUE TITLE
Add amenities and price text

### ISSUE THREAD

**Issue by moriz23** [moriz23/travel_site#28]
Add amenities (wi-fi, pool, etc) and prices to the given panels, just add it to the given syntax it will be shown in the master branch

 <div class="col-md-4">
    <div class="panel panel-default hotel-search">
      <div class="panel-heading">Amenities</div>
        <div class="panel-body">
          <div class="form-group">
            <div class="row-fluid">
              <input type="checkbox" value="">
              <br>
              <input type="checkbox" value=""> Add Amenities
              <br>
              <input type="checkbox" value=""> Add Amenities
              <br>
              <input type="checkbox" value=""> Add Amenities
              <br>
              <input type="checkbox" value=""> Add Amenities
            </div>
          </div>
        </div>
    </div>
  </div>

**Comment by C-Das** [comment]
We should change the search to modal search.
